[package]
name = "riscv"
version = "0.1.0"
edition = "2021"

[patch.crates-io]
riscv-rt = { git = "https://github.com/9names/riscv-rt", branch = "rv32e" }

[dependencies]
embedded-hal = "1.0.0"
panic-halt = "0.2.0"
# qingke-rt = "0.3.0"
riscv-rt = "0.11.0"

[profile.dev]
opt-level = "s"
